<!DOCTYPE html>
<html>

<head>
	<title>Studio-Komp - logowanie</title>
	<link rel="stylesheet" href="<?=DIR?>/css/main.css">
	<link rel="stylesheet" href="<?=DIR?>/css/font-awesome.min.css">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">
</head>
<body>
	<div style="position: absolute; top: 30%; left: 50%; margin-right: -50%; transform: translate(-50%, 0%) ">
		<div style="width:700px; background-color: #005279; padding: 8px 17px;">
			<span style="font: 13px Arial; color: #fff;">Studio-Komp - nowe urządzenie</span>
		</div>
		<div style="position:absolute;width:700px; height: 220px; padding-top:30px; background-color: #2E373F; display:flex;">
		    <span>Czekaj na akceptację urządzenia.</span>
		</div>
	</div>
</body>
</html>