<div class="overlay-window-background"></div>

<div class="overlay-window-content" style="width: 1080px;">
	<span class="overlay-window-title">Utwórz kategorię</span>
	<form id="create-category-form">
		<input id="category-name" type="text" name="category" style="color:black">
		<button type="submit">Dodaj</button>
		<button class="overlay-window-close" type="button">Zamknij</button>
	</form>
</div>