<div class="content-box">
	<h2 class="title">Klient</h2>
	<a class="button" href="<?= url('/customer/'.$customerId) ?>">Edytuj</a>
	<div>
		<span class="field-first label-gray-small">Numery telefonu</span>
		<span class="field label-gray-small">Imię i Nazwisko / Nazwa firmy</span>
		<span class="field label-gray-small">Email</span>
		<span class="field-last label-gray-small">Obcojęzyczny</span>
	</div>
	<div style="padding: 10px 0 0 5px;">
		<span class="field-first label"><?= $phone ?></span>
		<span class="field label"><?= $name ?></span>
		<span class="field label"><?= $email ?></span>
		<span class="field-last label"><?= $nonPolish ?></span>
	</div>
</div>