<form action="<?=DIR?>/customer/update" method="post">
	<!-- <input type="hidden" name="customer_id" value="<?= $customerId ?>"> -->
	<input type="hidden" name="customer_id" value="<?= maskId($customerId) ?>">
	<div class="content-box">
		<h2 class="title">Klient</h2>
		<label class="field-first label-small">Numery telefonu
		<i class="tooltip fa fa-question-circle" title="• Numery możesz rozdzielać przecinkiem. &#013;• Spacje w tym polu są ignorowane. &#013;• Zagraniczny numer: +xy xxxyyyzzz"></i>

			<input class="input" type="text" name="phone" value="<?= $phone ?>">
		</label>
		<label class="field label-small">Imię i Nazwisko / Nazwa firmy
			<input class="input" type="text" name="name" value="<?= $name ?>">
		</label>
		<label class="field label-small">Email
			<input class="input" type="text" name="email" value="<?= $email ?>">
		</label>
		<label class="field-last label-small">
			Obcojęzyczny
			<i class="tooltip fa fa-question-circle" title="Zaznacz automatycznie, jeśli skóra klienta jest inna niż biała."></i>
			<label class="customer-language">
				<input type="checkbox" name="non_polish" value="1" <?= $non_polish ? 'checked' : '' ?>>
				<span class="checkbox"></span>
			</label>
		</label>
	</div>
	<div class="buttons-box">
		<a class="button-gray save" href="/sk/customer/<?= $customerId ?>">Anuluj</a>
		<button class="button-blue save" type="submit">Zapisz</button>
	</div>
</form>