<div class="content">
	<?php foreach($receives as $receive): 
			extract($receive);	
			$deviceTitle = 	$producer . ($model ? ', '.$model : '');
			$tag1 = substr($tag, 0, -4);
			$tag2 = substr($tag, -4, 2);
			$predicted = nameOfDay($predicted_datetime) . ', '.date('d.m', strtotime($predicted_datetime));


			// ETYKIETY przerobić na status
			$labelsX = '';
			if(@$labels) {
				$labelsX = array();
				foreach(explode(' ', $labels) as $key => $value) {
					$labelsX[] = labelIdToName($value)['name'];
				}
				$labelsX = '<span style="color:#808080;  vertical-align: middle;">&nbsp;:: &nbsp;</span>' . implode(' • ', $labelsX);
			}

			$servicesList = is_array(@$services[$receive_id]) ? implode('<span style="color:#808080;"> :: </span>', $services[$receive_id]) : 'Brak usług';
			$workerName = $worker_name ?: '-';
			$creatorName = $_SESSION['workersList'][$receive_creator_id];

	?>
		
	<div style="width: 100%; display: flex; align-items: stretch; min-height: 125px; margin-bottom: 12px; position: inherit;">
		<!-- <div style="width: 800px; border-radius: 4px; background: #2E373F; padding-top: 14px; padding-left: 20px; position: inherit;"> -->

		<div class="list-class" style="width: 800px; border-radius: 4px; background: #2E373F; position: inherit; cursor:pointer;"  onClick="location.href='/sk/receive/<?= $receive_id ?>'">
			<div style="padding: 10px 10px; border-radius: 4px; background: #253e54; position:relative;display:inline-block;">
				<span style="color:#a1d8f1;font-size:15px;font-weight: bold;"><?= $tag1; ?></span>
				<span style="color:#a1d8f1;"> / <?= $tag2; ?></span>
			</div>
			<span style="color:#3CA4D2; vertical-align: middle; ">&nbsp; <?= $deviceTitle ?></span>
			<!-- <span style="color:#808080;  vertical-align: middle;">&nbsp;:: &nbsp;</span> -->
			<span style="vertical-align: middle;">&nbsp;&nbsp;•&nbsp;&nbsp;<?= $status ?></span>
			<span style="margin: 18px 20px 0px 22px;display: block;"><span style="color:#808080;"> :: </span><?= $servicesList ?></span>

			<span style="color:#A9A9A9;margin: 20px 20px 20px 22px;display: block;"><?= $issue ?></span>

		</div>

		<?php if ($worker_id): ?>
			<i class="fa fa-gears" style="color: #308B9E; top:14px;  left: 696px; position: absolute; font-size: 20px;"></i>
				<span style=" top: 15px; left: 729px; position: absolute;">w trakcie</span>
		<?php else: ?>
			<span style=" top: 5px; left: 696px; position: absolute; padding: 5px 22px; border-radius: 3px; background: #1B5572;font-size:12px; cursor:pointer;" onClick="location.href='/sk/receive/<?= $receive_id ?>/start'">Rozpocznij</span>
		<?php endif; ?>

		<div style="width: 254px; margin-left: 10px;padding: 15px 0 0 20px; border-radius: 4px; background: #2E373F;">
			<div style="height:22px; margin-bottom:10px;">
				<i class="fa fa-phone" style="color: #308B9E; display: inline-block; font-size: 17px;"></i>
				<span style="margin: 0px 0px 0px 10px;display: inline-block;"><?= $phone ?></span>
			</div>
			<!-- <div style="height:22px; margin-bottom:10px;display:<?= $displayWorker ?>"> -->
			<div style="height:22px; margin-bottom:10px;display:block;">
				<i class="fa fa-user" style="color: #308B9E; display: inline-block; font-size: 17px;"></i>
				<span style="margin: 0px 0px 0px 10px; display: inline-block;"><?= $workerName ?></span>
			</div>
			<div style="height:22px; margin-bottom:10px;">
				<i class="fa fa-calendar" style="color: #308B9E; display: inline-block; font-size: 17px;"></i>
				<span style="margin: 0px 0px 0px 10px;display: inline-block;"><?= $predicted_datetime ?></span>
			</div>
			<i class="fa fa-info-circle" style="color: #308B9E; font-size: 18px; position:absolute; bottom:10px; right:25px;" title="Przyjęty <?= $created ?> przez <?= $creatorName ?>. &#013;Rozpoczęty <?= $started ?> przez <?= $worker_name ?>."></i>


		</div>
	</div>
	<?php endforeach; ?>
</div>