			<div class="content-box history">
				<h2 class="title">Powiązane naprawy (<?= count($relatedReceives) ?>)</h2>
				<i class="ico-test fa fa-caret-up"></i>
				<div class="animate">
					<table class="history-list">
						<?php foreach($relatedReceives as $receive):
								extract($receive);
						?>
							<tr class="row">
								<td class="col col1"><?= $sticker ?></td>
								<td class="col col2"><?= $issue ?></td>
								<td class="col col3"><?= $finished ?></td>
							</tr>
						<?php endforeach; ?>	
					</table>
				</div>
			</div>

			<div id="part-add-windowX" style="display:none; position: absolute; top: 30%; left: 50%; margin-right: -50%; transform: translate(-50%, 0%); z-index:11; ">
					<div style="width:696px; height:16px; background-color: #005279; padding: 8px 17px;">
						<span style="font: 13px Arial; color: #fff;">Nowy zakup</span>
					</div>

					<div style="position:absolute;width:698px; background-color: #2E373F; padding: 20px 16px; height:264px;">
						<form autocomplete="off" method="post" action="/sk/part/<?= $id ?>/add">
							<input type="hidden" id="part-id" name="part[id]" value="">
							<div style="width:660px; padding:0 10px; margin-right:14px;">
								<span class="content-block-text">Link</span>
								<input type="text" id="part-url" class="form-input input-form " style="width:100%;" name="part[url]">
							</div>

							<div style="display:inline-block; width:356px; padding:0 10px;margin-right:14px;">

								<span class="content-block-text">Nazwa</span>
								<input type="text" id="part-name" class="form-input input-form " style="width:100%;" name="part[name]" >

								<div style="display:inline-block; width:60px; margin-right:28px;">
									<span class="content-block-text">Cena</span>
									<input id="part-price" type="text" class="form-input input-form" style="width:100%;" name="part[price]">
								</div>
								<div style="display:inline-block;width:157px; margin-right:28px;">
									<span class="content-block-text">Sprzedawca</span>
									<input type="text" class="form-input input-form" style="width:100%;" name="part[seller]">
								</div>
								<div style="display:inline-block;width:120px; position:absolute; left:310px; ">                                    
									<label class="checkbox2-label" style="margin-left: 2px; top:25px;">
										<input type="checkbox" name="part[is_used]">
										<span class="checkbox2"></span>
									</label>
									<span class="content-block-text">Używany</span>
								</div>
							</div>

							<div style="display:inline-block; position:absolute; width:270px; padding:0 10px; margin-right:14px;">
								<span class="content-block-text">Uwagi</span>
								
								<textarea class="input-form" name="part[notice]" style="width:100%; min-height: 87px; resize: none;;"></textarea>
							</div>


							<div>

								<button class="button" type="submit" style="margin-left: 10px; height:27px; width:auto; position:absolute; right:36px; bottom: 25px; padding: 0 30px;">Dodaj</button>
								<button class="button-2" type="reset" style="margin-left: 10px; height:27px; width:auto; position:absolute; right:138px; bottom: 25px; padding: 0 30px;">Reset</button>

							</div>
							<span class="content-block-text" style="position:absolute; left: 27px; bottom:17px; font-weight:800; text-align:left;width:auto; cursor:pointer;" onclick="togglePartAdd()">Powrót</span>
						</form>
					</div>
					
				</div>