<div class="content-box note-box">
	<h2 class="title">Notatki (<?= count($notes) ?>)</h2>
	<i class="ico-test fa fa-caret-up"></i>
	<div class="animate">
		<form class="note" id="note-create" action="/sk/note/create" method="post">
			<input type="hidden" name="receive_id" value="<?= $receiveId ?>">
			<input type="hidden" name="note_id" value="">
			<div class="avatar-box">
				<div class="avatar" style="background-image: url('https://media.creativemornings.com/uploads/user/avatar/246995/151103_Self_Portrait_50x50_72.jpg')"></div>
			</div>
			<div class="content-note">
				<span class="author"><?= getFromSession('workerName') ?> &nbsp;•&nbsp; Pracownik</span>
				<textarea class="content-input note-edit" name="note"></textarea>
				<span class="error-message hidden"></span>
			</div>
			<div class="add-btn-box">
				<button class="button-blue add-note-btn" type="submit">Dodaj notatkę</button>
			</div>
			<div class="edit-btn-box hidden">
				<span class="date"></span>
				<div class="icon-box">
					<button class="ico star fa fa-star-o" title="Przypnij"></button>
					<button class="button-blue update-btn hidden">Aktualizuj</button>
					<button class="ico fa fa-edit note-edit-btn" type="button"></button>
					<button class="ico fa fa-trash note-delete-btn" title="Usuń" type="button"></button>
					<a class="button-blue delete-confirm-btn hidden" href="/sk/note/%id/delete">Potwierdź usunięcie</a>
					<button class="ico fa fa-ban note-cancel-btn hidden" title="Anuluj" type="button"></button>
				</div>
			</div>
		</form>

		<?php foreach($notes as $note): ?>
		<?php $pinned = $note['pinned'] ? 'pinned' : ''; ?>
		<?php $star = $note['pinned'] ? 'fa-star' : 'fa-star-o'; ?>

		<form class="note <?= $pinned ?>" action="/sk/note/edit" method="post">
			<input type="hidden" name="note_id" value="<?= $note['id'] ?>">
			<div class="avatar-box">
				<div class="avatar"><?= $note['worker_short'] ?></div>
			</div>
			<div class="content-note">
				<span class="author"><?= $note['worker_name'] ?> &nbsp;•&nbsp; Pracownik</span>
				<textarea class="content-input note-read" name="note" disabled><?= $note['note'] ?></textarea>
				<span class="error-message"></span>

			</div>
			<div>
				<span class="date"><?= $note['created'] ?></span>
				<div class="icon-box">
					<button class="ico star fa <?= $star ?>" title="Przypnij"></button>
					<button class="button-blue update-btn hidden">Aktualizuj</button>
					<button class="ico fa fa-edit note-edit-btn" type="button"></button>
					<button class="ico fa fa-trash note-delete-btn" title="Usuń" type="button"></button>
					<a class="button-blue delete-confirm-btn hidden" href="/sk/note/<?= $note['id'] ?>/delete">Potwierdź usunięcie</a>
					<button class="ico fa fa-ban note-cancel-btn hidden" title="Anuluj" type="button"></button>
				</div>
			</div>
		</form>
		<?php endforeach; ?>
	</div>
</div>