<?php

$allowChangeWorker = true;
$allowEdit = true;
$allowDelete = true;

?>

<div class="content-box">
	<!-- <h2 class="title">Zaproponowane rozwiązania</h2> -->
	<form class="form-test" action="/sk/service/create" method="post" style="width: inherit;">
		<input type="hidden" name="receiveId" value="<?= $receiveId ?>">

		<table class="solutions-list" data-id="0" data-count="0">
			<tr>
				<th class="head-solution">Zaproponowane rozwiązanie</th>
				<th class="head-price">Koszt</th>
				<th class="head-status">Status</th>
				<th class="head-worker">Pracownik</th>
				<th class="head-buttons">Akcje</th>
			</tr>
			<!-- template hidden-->
			<tr class="row hidden"> 
				<td style="padding-left: 24px; position: relative;" >
					<input class="input input-name input-edit" name="" value="" autocomplete="off">
					<span class="char-count hidden">3</span>
					<div class="prompt-box hidden">
						<div class="template" tabindex="1">
							<span class="name"></span>
							<span class="price"></span> zł
						</div>
					</div>
				</td>
				<td class="">
					<input class="input input-cost input-edit" name="" value="" autocomplete="off">
				</td>
				<td colspan="2"></td>
				<td>
					<a class="ico fa fa-trash solution-delete" title="Usuń"></a>
				</td>
			</tr>
			<?php foreach ($services as $service): 
				$priceTest = 'price';

				switch ($service['status']) {
					case 'opened':
						$status = '-';
						break;
					case 'finished':
						$status = 'Zrobione';
						break;
					case 'part_ordered':
						$status = 'Część zamówiona';
						break;
					case 'canceled':
						$status = 'Rezygnacja';
						$priceTest = null;
						break;
					case 4:
						$status = 'Usunięte';
						$priceTest = null;
						break;
					case 5:
						$status = 'Delegacja';
						break;
					default:
						$status = 'Unknown';
				}

				if($service['deleted']) {
					$status = 'Usunięte';
					$priceTest = null;
				}

				if ($service['worker_id'] == 0) {
					$workerName = '-';
				} elseif ($service['worker_id'] == $workerId) {
					$workerName = 'Ty';
				} else {
					// $workerName = workersList($service['worker_id']);
					$workerName = $service['workerName'];

				}

				// to chyba tymczasowo
				$workersList = $_SESSION['workersList'];
				natcasesort($workersList);
			?>
			<tr class="row" data-service_id="<?= $service['id'] ?>">
				<td style="padding-left: 24px" ><input class="input input-read" name="name" value="<?= $service['name'] ?>" disabled></td>
				<td class=""><input class="input input-read input-cost <?= $priceTest ?>" name="price" value="<?= $service['price'] ?>" disabled></td>
				<td class=""><?= $status ?></td>
				<td class="">
					<div class="worker-name-test"><?= $workerName ?></div>
					<select class="input select delegate" style="font-size: 12px; padding: 3px; width: 135px; display: none; margin: 0;" size="1" data-worker_id="<?= $service['worker_id'] ?>" >
						<?php foreach($workersList as $key => $worker): ?>
							<option value="<?= $key ?>"><?= $worker?></option>
						<?php endforeach; ?>
					</select>
				</td>
				<td class="">
					<div class="action-buttons">
					<?php

						if ($actionButtons) {

							if ($service['status'] == 'finished') {
								print '<a class="ico fa fa-check" title="Cofnij oznaczenie ukończenia" href="/sk/service/'. $service['id'] .'/incomplete"></a>';

							} elseif ($service['status'] == 'canceled') {
								print '<a class="ico fa fa-frown-o" title="Cofnij rezygnację z naprawy" href="/sk/service/'. $service['id'] .'/restore"></a>';

							} elseif ($service['deleted']) {
								print '<a class="ico fa fa-trash" title="Przywróć" href="/sk/service/'. $service['id'] .'/recover"></a>';

							} else {
								print '<a class="ico fa fa-check" title="Oznacz jako ukończone" href="/sk/service/'. $service['id'] . '/complete"></a>';

								if ($service['part_id']) {
									print '<a class="ico fa fa-plug" title="Odłącz część" href="/sk/service/'. $service['id'] .'/unplug-part/"></a>';
								} else {
									print '<a class="ico fa fa-wrench" title="Przypisz część" href="#" onclick="assignPart('. $service['id'] .');"></a>';

								}
								

								print '<a class="ico fa fa-frown-o" title="Rezygnacja z tej naprawy" href="/sk/service/'. $service['id'] .'/cancel"></a>';


								if ($allowEdit) {
									print '<a class="ico fa fa-edit solution-edit" title="Edytuj"></a>';

								}

								if ($allowDelete) {
									print '<a class="ico fa fa-trash" title="Usuń" href="/sk/service/'. $service['id'] .'/delete"></a>';
								}

								if ($allowChangeWorker) {
									print '<i class="ico fa fa-user-plus change-worker-button" title="Zmień pracownika"></i>';
								}

							}
						} else {
							print '-';
						}
					?>
					</div>
					<div class="edit-buttons hidden">
						<a class="ico fa fa-save solution-update-btn" title="Aktualizuj"></a>
						<a class="ico fa fa-times solution-edit-end" title="Anuluj"></a>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
			<!-- </tr> -->
			<tr class="buttons" style="line-height: 28px;">
				<td class="kek" style="text-align: right; padding-right: 10px;">
					<button class="button add-solution" style="position: absolute; left:27px; bottom: 13px; top:auto; width:80px;" type="button">Dodaj</button>
					<button class="button solution-save-btn hidden" style="position: absolute; left:118px; bottom: 13px; top:auto; width:80px;" type="button">Zapisz</button>
					<span>RAZEM</span>
				</td>
				<td class="price-total" style="padding-left: 8px;">0 PLN</td>
			</tr>
		</table>
	</form>
</div>